import Accordion from '@/components/ui/accordion';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="absolute flex top-[60px] left-0 right-0 bottom-0">
          <Accordion />
          <div className="relative left-[250px] grow overflow-auto bg-gray-500  min-w-[900px]">{children}</div>
        </main>
      </body>
    </html>
  );
}
